#!/bin/bash
# Validates that local environment matches Amplify production
# Run this BEFORE deploying to catch config drift

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=============================================="
echo "  Pre-Deploy Validation"
echo "=============================================="

ERRORS=0

# 1. Check Node version matches Amplify (20.x)
echo -n "Checking Node version... "
NODE_VER=$(node --version | cut -d. -f1 | tr -d 'v')
if [ "$NODE_VER" -ge 18 ] && [ "$NODE_VER" -le 20 ]; then
    echo -e "${GREEN}OK${NC} (v$NODE_VER)"
else
    echo -e "${RED}MISMATCH${NC} - Amplify uses Node 18-20, you have $(node --version)"
    ERRORS=$((ERRORS+1))
fi

# 2. Check .env.local exists
echo -n "Checking .env.local exists... "
if [ -f .env.local ]; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}MISSING${NC} - Create .env.local with production values"
    ERRORS=$((ERRORS+1))
fi

# 3. Check all required env vars are set locally
echo "Checking environment variables..."
REQUIRED_VARS=(
    "NEXT_PUBLIC_API_ENDPOINT"
    "NEXT_PUBLIC_AWS_REGION"
    "NEXT_PUBLIC_IDENTITY_POOL_ID"
    "NEXT_PUBLIC_USER_POOL_CLIENT_ID"
    "NEXT_PUBLIC_USER_POOL_ID"
)

for VAR in "${REQUIRED_VARS[@]}"; do
    echo -n "  $VAR... "
    if grep -q "^$VAR=" .env.local 2>/dev/null; then
        echo -e "${GREEN}OK${NC}"
    else
        echo -e "${RED}MISSING${NC}"
        ERRORS=$((ERRORS+1))
    fi
done

# 4. TypeScript compilation check
echo -n "Checking TypeScript compilation... "
if npm run build > /tmp/build.log 2>&1; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}FAILED${NC}"
    echo "Build errors:"
    tail -20 /tmp/build.log
    ERRORS=$((ERRORS+1))
fi

# 5. Check for console.log statements (optional warning)
echo -n "Checking for console.log statements... "
CONSOLE_COUNT=$(grep -r "console\.log" app/ components/ lib/ --include="*.ts" --include="*.tsx" 2>/dev/null | wc -l)
if [ "$CONSOLE_COUNT" -gt 0 ]; then
    echo -e "${YELLOW}WARNING${NC} - $CONSOLE_COUNT console.log statements found"
else
    echo -e "${GREEN}OK${NC}"
fi

# 6. Check amplify_outputs.json exists (it's gitignored, generated by backend deploy)
echo -n "Checking amplify_outputs.json exists... "
if [ -f amplify_outputs.json ]; then
    echo -e "${GREEN}OK${NC} (exists locally)"
else
    echo -e "${RED}MISSING${NC} - Run: npx ampx sandbox or deploy backend first"
    ERRORS=$((ERRORS+1))
fi

echo "=============================================="
if [ $ERRORS -eq 0 ]; then
    echo -e "${GREEN}All checks passed! Safe to deploy.${NC}"
    exit 0
else
    echo -e "${RED}$ERRORS error(s) found. Fix before deploying.${NC}"
    exit 1
fi
