AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Kalshi Dashboard API - Multi-user trading dashboard with admin support

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 256
    Environment:
      Variables:
        TRADES_TABLE: production-kalshi-trades-v2
        POSITIONS_TABLE: production-kalshi-market-positions
        PORTFOLIO_TABLE: production-kalshi-portfolio-snapshots
        MARKET_METADATA_TABLE: production-kalshi-market-metadata
        CONFIG_BUCKET_NAME: production-kalshi-trading-config

Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool for authentication
    Default: 'arn:aws:cognito-idp:us-east-1:355149669325:userpool/us-east-1_WEozUeojc'
  
  PortfolioFetcherLayerArn:
    Type: String
    Description: ARN of the PortfolioFetcherLayer from kalshi-market-capture stack
    Default: ''  # Will be populated during deployment

Resources:
  # API Gateway
  DashboardApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: kalshi-dashboard-api
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
            Identity:
              Header: Authorization
        AddDefaultAuthorizerToCorsPreflight: false

  # Lambda: Get Trades
  GetTradesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-get-trades
      CodeUri: ./
      Handler: get-trades.lambda_handler
      Description: Get trade history for a market ticker
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Layers:
        - !Ref SharedCodeLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: production-kalshi-trades-v2
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:us-east-1:355149669325:table/production-kalshi-trades-v2/index/*
      Events:
        GetTrades:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /trades
            Method: GET

  # Lambda: Get Portfolio
  GetPortfolioFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-get-portfolio
      CodeUri: ./
      Handler: get-portfolio.lambda_handler
      Description: Get portfolio data for user(s)
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Layers:
        - !Ref SharedCodeLayer
        - !Ref PortfolioFetcherLayerArn
      Environment:
        Variables:
          RATE_LIMITER_TABLE_NAME: production-kalshi-rate-limiter
          USER_SECRET_PREFIX: production/kalshi/users
          KALSHI_API_BASE_URL: https://api.elections.kalshi.com
          POSITIONS_LIVE_TABLE: production-kalshi-positions-live
      Policies:
        - DynamoDBReadPolicy:
            TableName: production-kalshi-market-positions
        - DynamoDBReadPolicy:
            TableName: production-kalshi-positions-live
        - DynamoDBReadPolicy:
            TableName: production-kalshi-portfolio-snapshots
        - DynamoDBReadPolicy:
            TableName: production-kalshi-market-metadata
        - DynamoDBReadPolicy:
            TableName: production-kalshi-trades-v2
        - DynamoDBCrudPolicy:
            TableName: production-kalshi-rate-limiter
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:us-east-1:355149669325:table/production-kalshi-trades-v2/index/*
        - S3ReadPolicy:
            BucketName: production-kalshi-trading-config
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - arn:aws:secretsmanager:us-east-1:355149669325:secret:production/kalshi/users/*
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:ListSecrets
              Resource: '*'  # ListSecrets requires wildcard
      Events:
        GetPortfolio:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /portfolio
            Method: GET

  # Lambda: Get Analytics
  GetAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-get-analytics
      CodeUri: ./
      Handler: get-analytics.lambda_handler
      Description: Get analytics data (PnL by category)
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Layers:
        - !Ref SharedCodeLayer
      Environment:
        Variables:
          SETTLEMENTS_TABLE: production-kalshi-settlements
          MARKET_METADATA_TABLE: production-kalshi-market-metadata
      Policies:
        - DynamoDBReadPolicy:
            TableName: production-kalshi-settlements
        - DynamoDBReadPolicy:
            TableName: production-kalshi-market-metadata
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - arn:aws:secretsmanager:us-east-1:355149669325:secret:production/kalshi/users/*
      Events:
        GetAnalytics:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /analytics
            Method: GET

  # Lambda: Trading Status (get/set trading shutdown signal)
  TradingStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-trading-status
      CodeUri: ./
      Handler: trading-status.lambda_handler
      Description: Get and set trading shutdown status (admin only for POST)
      AutoPublishAlias: live
      # ProvisionedConcurrencyConfig temporarily removed due to CloudFormation issues
      # Re-enable after deployment stabilizes:
      # ProvisionedConcurrencyConfig:
      #   ProvisionedConcurrentExecutions: 1
      Layers:
        - !Ref SharedCodeLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: production-kalshi-trading-shutdown-signals
        - S3ReadPolicy:
            BucketName: production-kalshi-trading-config
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:ListSecrets
              Resource: '*'  # ListSecrets requires wildcard
      Events:
        GetTradingStatus:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /trading-status
            Method: GET
        SetTradingStatus:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /trading-status
            Method: POST

  # Lambda: Admin Stats (market capture runs, recent orders/trades)
  AdminStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-admin-stats
      CodeUri: ./
      Handler: get-admin-stats.lambda_handler
      Description: Get admin statistics (market capture runs, recent orders/trades)
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Layers:
        - !Ref SharedCodeLayer
      Environment:
        Variables:
          ORDERS_TABLE: production-kalshi-orders
          TRADES_TABLE: production-kalshi-trades-v2
          MENTION_EVENTS_TABLE: production-kalshi-mention-events
      Policies:
        - DynamoDBReadPolicy:
            TableName: production-kalshi-orders
        - DynamoDBReadPolicy:
            TableName: production-kalshi-trades-v2
        - DynamoDBReadPolicy:
            TableName: production-kalshi-mention-events
        - Statement:
            - Effect: Allow
              Action:
                - cloudwatch:GetMetricStatistics
              Resource: '*'
      Events:
        GetAdminStats:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /admin-stats
            Method: GET

  # Lambda: Volatile Watchlist (high-confidence volatility tracking)
  VolatileWatchlistFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-volatile-watchlist
      CodeUri: ./
      Handler: get-volatile-watchlist.lambda_handler
      Description: Get volatile watchlist entries (admin only)
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Layers:
        - !Ref SharedCodeLayer
      Environment:
        Variables:
          WATCHLIST_TABLE: production-kalshi-volatile-watchlist
          MARKET_METADATA_TABLE: production-kalshi-market-metadata
      Policies:
        - DynamoDBCrudPolicy:
            TableName: production-kalshi-volatile-watchlist
        - DynamoDBReadPolicy:
            TableName: production-kalshi-market-metadata
      Events:
        GetVolatileWatchlist:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /volatile-watchlist
            Method: GET

  # Lambda: Mention Monitors (get/clear mention monitor status)
  MentionMonitorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-mention-monitors
      CodeUri: ./
      Handler: mention-monitors.lambda_handler
      Description: Get and clear mention monitor status (admin only)
      Timeout: 60
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Environment:
        Variables:
          MENTION_STATE_TABLE: production-kalshi-mention-event-state
          ECS_CLUSTER: production-kalshi-fargate-cluster
      Policies:
        - DynamoDBCrudPolicy:
            TableName: production-kalshi-mention-event-state
        - Statement:
            - Effect: Allow
              Action:
                - ecs:StopTask
                - ecs:DescribeTasks
              Resource: '*'
              Condition:
                ArnLike:
                  ecs:cluster: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/production-kalshi-fargate-cluster'
      Events:
        GetMentionMonitors:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /mention-monitors
            Method: GET
        ClearMentionMonitors:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /mention-monitors/clear
            Method: POST

  # Lambda: Voice Trader Router (launch/manage voice trading containers)
  VoiceTraderRouterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dashboard-voice-trader-router
      CodeUri: ./
      Handler: voice-trader-router.lambda_handler
      Description: Launch and manage voice trading containers for mention markets
      Timeout: 60
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Environment:
        Variables:
          ECS_CLUSTER: production-kalshi-fargate-cluster
          TASK_FAMILY: production-voice-mention-trader
          VOICE_TRADER_STATE_TABLE: production-kalshi-voice-trader-state
          MENTION_EVENTS_TABLE: production-kalshi-mention-events
          MARKET_METADATA_TABLE: production-kalshi-market-metadata
          SUBNETS: subnet-0ba02a0291289ed61
          SECURITY_GROUPS: sg-056792d76ef21c4c5
          VOICE_TRADER_EC2_INSTANCE_ID: i-0ae0218a057e5b4c3
      Policies:
        - DynamoDBCrudPolicy:
            TableName: production-kalshi-voice-trader-state
        - DynamoDBReadPolicy:
            TableName: production-kalshi-mention-events
        - DynamoDBReadPolicy:
            TableName: production-kalshi-market-metadata
        - Statement:
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:StopTask
                - ecs:DescribeTasks
                - ecs:ListTasks
              Resource: '*'
              Condition:
                ArnLike:
                  ecs:cluster: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/production-kalshi-fargate-cluster'
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:role/production-voice-mention-trader-task-execution-role'
                - !Sub 'arn:aws:iam::${AWS::AccountId}:role/production-voice-mention-trader-task-role'
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - arn:aws:secretsmanager:us-east-1:355149669325:secret:production/kalshi/users/*
        - Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeNetworkInterfaces
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:StartInstances
                - ec2:StopInstances
                - ec2:RebootInstances
              Resource: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/i-0ae0218a057e5b4c3'
        - Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - ssm:SendCommand
                - ssm:GetCommandInvocation
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}::document/AWS-RunShellScript'
                - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/i-0ae0218a057e5b4c3'
      Events:
        GetEvents:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/events
            Method: GET
        LaunchSession:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/launch
            Method: POST
        GetStatus:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/status/{session_id}
            Method: GET
        StopSession:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/stop/{session_id}
            Method: POST
        DialSession:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/dial/{session_id}
            Method: POST
        RedialSession:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/redial/{session_id}
            Method: POST
        EC2Status:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/ec2/status
            Method: GET
        EC2Start:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/ec2/start
            Method: POST
        EC2Stop:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/ec2/stop
            Method: POST
        EC2Reboot:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/ec2/reboot
            Method: POST
        EC2Launch:
          Type: Api
          Properties:
            RestApiId: !Ref DashboardApi
            Path: /voice-trader/ec2/launch
            Method: POST

  # Lambda Layer: Shared code (s3_config_loader)
  SharedCodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dashboard-shared-code
      Description: Shared utilities (s3_config_loader)
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${DashboardApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
  
  GetTradesFunctionArn:
    Description: Get Trades Lambda ARN
    Value: !GetAtt GetTradesFunction.Arn
  
  GetPortfolioFunctionArn:
    Description: Get Portfolio Lambda ARN
    Value: !GetAtt GetPortfolioFunction.Arn

  GetAnalyticsFunctionArn:
    Description: Get Analytics Lambda ARN
    Value: !GetAtt GetAnalyticsFunction.Arn
